export const SET_TASKS_OPEN = 'SET_TASKS_OPEN'
export const SET_TASKS_PROGRESS = 'SET_TASKS_PROGRESS'
export const SET_TASKS_COMPLETED = 'SET_TASKS_COMPLETED'
export const SET_TASKS_REJECTED = 'SET_TASKS_REJECTED'
